/*
 * \file aos-boards_release.h
 *
 * \brief AOS aos-boards release version constants.
 *
 * \details This file defines the aos release version constants. It is
 *          automatically created by the release script.
 *
 * \note This file is automatically generated - do not change manually.
 *
 * \copyright (c)2022, Abeeway (www.abeeway.com).  All Rights Reserved.
 *
 */
#pragma once

#define AOS_BOARDS_RELEASE_GITVERSION "2022.11.29"
#define AOS_BOARDS_RELEASE_BUILD_DATE 20221129
#define AOS_BOARDS_RELEASE_BUILD_TIME 142111

