/*
 * \file aos-core_release.h
 *
 * \brief AOS aos-core release version constants.
 *
 * \details This file defines the aos release version constants. It is
 *          automatically created by the release script.
 *
 * \note This file is automatically generated - do not change manually.
 *
 * \copyright (c)2022, Abeeway (www.abeeway.com).  All Rights Reserved.
 *
 */
#pragma once

#define AOS_CORE_RELEASE_GITVERSION "2022.08.18"
#define AOS_CORE_RELEASE_BUILD_DATE 20220818
#define AOS_CORE_RELEASE_BUILD_TIME 115912

