/*
 * \file aos-services_release.h
 *
 * \brief AOS aos-services release version constants.
 *
 * \details This file defines the aos release version constants. It is
 *          automatically created by the release script.
 *
 * \note This file is automatically generated - do not change manually.
 *
 * \copyright (c)2022, Abeeway (www.abeeway.com).  All Rights Reserved.
 *
 */
#pragma once

#define AOS_SERVICES_RELEASE_GITVERSION "Alpha-release"
#define AOS_SERVICES_RELEASE_BUILD_DATE 20220705
#define AOS_SERVICES_RELEASE_BUILD_TIME 153227

